version: "3.9"
services:
  backend:
    build: ./backend
    container_name: acme_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/productdb
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped

  worker:
    build: ./backend
    container_name: acme_worker
    command: ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info", "--concurrency=1"]
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/productdb
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: acme_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5434:5432"
    volumes:
      - acme_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: acme_redis
    ports:
      - "6378:6379"
    volumes:
      - acme_redis_data:/data

volumes:
  acme_postgres_data:
  acme_redis_data:
